version: '3.8'
services:
  barbeiros-dev-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: barbeiros
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    user: root
    networks:
      - guusta
  # test-db:
  #   image: postgres:13
  #   ports:
  #     - 5435:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: nest-estudo
  #   networks:
  #     - guusta    
networks:
  guusta: